PROJECT_SOURCEFILES += reliable_flood_neighbor_req.c neighbors.c packet_buffer.c packet.c

#CC=gcc
#CFLAGS=-c -Wall
#LDFLAGS=
#SOURCES=packet_buffer_unittest.c packet_buffer.c ../base/queue_buffer.c
#OBJECTS=$(SOURCES:.c=.o)
#INCLUDES=../ -I../../third_party/contiki-2.4/core
#EXECUTABLE=main
#
#all: $(EXECUTABLE)
#
#$(EXECUTABLE): $(OBJECTS)
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@
#
#%.o: %.c
#	$(CC) -c -I $(INCLUDES) $(CFLAGS) $< -o $@
