/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Tellstick */

#ifndef _Included_Tellstick
#define _Included_Tellstick
#ifdef __cplusplus
extern "C" {
#endif
#undef Tellstick_TELLSTICK_TURNON
#define Tellstick_TELLSTICK_TURNON 1L
#undef Tellstick_TELLSTICK_TURNOFF
#define Tellstick_TELLSTICK_TURNOFF 2L
#undef Tellstick_TELLSTICK_LEARN
#define Tellstick_TELLSTICK_LEARN 32L
/*
 * Class:     Tellstick
 * Method:    tdOpen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tellstick_tdOpen
  (JNIEnv *, jobject);

/*
 * Class:     Tellstick
 * Method:    tdClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tellstick_tdClose
  (JNIEnv *, jobject);

/*
 * Class:     Tellstick
 * Method:    tdTurnOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdTurnOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdTurnOff
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdTurnOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdLearn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Tellstick_tdLearn
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdBell
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdBell
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdDim
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdDim
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Tellstick
 * Method:    tdMethods
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Tellstick_tdMethods
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Tellstick
 * Method:    tdGetNumberOfDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tellstick_tdGetNumberOfDevices
  (JNIEnv *, jobject);

/*
 * Class:     Tellstick
 * Method:    tdGetDeviceId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Tellstick_tdGetDeviceId
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdGetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Tellstick_tdGetName
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tellstick
 * Method:    tdSetName
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdSetName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     Tellstick
 * Method:    tdAddDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tellstick_tdAddDevice
  (JNIEnv *, jobject);

/*
 * Class:     Tellstick
 * Method:    tdRemoveDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Tellstick_tdRemoveDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
